* Geography:

- Location: Give precise geographical information (where exactly on the continent, bordering countries, bordering seas/oceans)

- Map References: continent it is located in

** Area:

*** Total: If you have a precise number, if not, what rank is it in terms of size?

*** Comparative: give real-world references for size, you can also use other countries from your world

Climate: Give a precise description of your country's climate(s)

Terrain: Give informations about mountains, plains, etc...

Natural Resources: Ores, animals, special lands, etc...

** Natural Hazards:

- Geographical Notes: Things that don't fit into any other categories but are still notable

* People and Society:

- Nationality: What the people are called, the adjective given

- Ethnicities: Majority and minorities

- Languages: Official languages, dialects

- Religions: Percentages, is there a state religion?

- Population: How many people live there?

- Age structure:

  - 0-20: percentage

  - 20-50: percentage

  - 50-65: percentage

  - 65+: percentage

- Median age: Average age for the population

- Life expectancy: What age can people hope of getting to?

- Fertility: How many children, in average, per woman

* Government:

- Name: Short and long form, local name, short and long

- Government type:

- Capital:

- Dependent areas: Overseas territories, colonies, etc...

- National Holiday: Date, Background

- Citizenship: Is it given at birth? Can you have it by descent? Can you have multiple citizenships? Can you have naturalization, when?

- Suffrage: Voting age, if voting exists

- Executive branch:

** Head of state: Who represents the state: Position and name

** Head of government: Who runs the government: Position and name

** Elections: Describe the election process

- Legislative branch:

*** Description:

*** Elections:

- Flag description:

- National Symbols:

- National anthem: Name and history

** Economy:

- Overview: Give a detailed overview of the nation's economy

- GDP: Give your nation's total GDP and its rank in the world, you can go more in-depth if you want: growth, per capita, saving and composition

- Agriculture: What are your country's main revenue sources from agriculture

- Industries: What are your country's main revenue sources from industry

- Labour force: How many people are working, what's the worldwide rank? What are the occupation percentages?

- Budget: Revenues and expenditures

- Notes: Other informations about your country's economy

** Military and Security:

- Military branches: Give the military's different branches and their names

- Service age: What is the minimum age to join the military, what are the genders? Is there conscription or service obligation?

- Military expenditures: military budget and world rank

- Nuclear armament: Is it a nuclear power? How many weapons? What is the world rank?

- Disputes: National and worldwide conflicts, with whom? Any territorial disputes?

- Illicit Drugs:
